baseURL: https://dallascard.github.io/granular-material/
languageCode: en-us
title: Granular Material
theme: pixyll

smartDashes: true


relativeurls: true
canonifyurls: true
contentDir: "content"

blackfriday:
    angledQuotes: true
    hrefTargetBlank: true

taxonomies:
    tag: "tags"

params:
    mainSections: ["post"]
    twitter_username: "dallascard"
    paginate: 4
    search_engine: false


